/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package dev.mochahaulier.clientproductservice.event;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ClientProductCreatedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6088739992604298896L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ClientProductCreatedEvent\",\"namespace\":\"dev.mochahaulier.clientproductservice.event\",\"fields\":[{\"name\":\"clientProductId\",\"type\":\"long\"},{\"name\":\"initialBalance\",\"type\":{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":20,\"scale\":2}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();
static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.DecimalConversion());
  }

  private static final BinaryMessageEncoder<ClientProductCreatedEvent> ENCODER =
      new BinaryMessageEncoder<ClientProductCreatedEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ClientProductCreatedEvent> DECODER =
      new BinaryMessageDecoder<ClientProductCreatedEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ClientProductCreatedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ClientProductCreatedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ClientProductCreatedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ClientProductCreatedEvent>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ClientProductCreatedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ClientProductCreatedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ClientProductCreatedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ClientProductCreatedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long clientProductId;
   private java.math.BigDecimal initialBalance;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ClientProductCreatedEvent() {}

  /**
   * All-args constructor.
   * @param clientProductId The new value for clientProductId
   * @param initialBalance The new value for initialBalance
   */
  public ClientProductCreatedEvent(java.lang.Long clientProductId, java.math.BigDecimal initialBalance) {
    this.clientProductId = clientProductId;
    this.initialBalance = initialBalance;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return clientProductId;
    case 1: return initialBalance;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      new org.apache.avro.Conversions.DecimalConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: clientProductId = (java.lang.Long)value$; break;
    case 1: initialBalance = (java.math.BigDecimal)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'clientProductId' field.
   * @return The value of the 'clientProductId' field.
   */
  public long getClientProductId() {
    return clientProductId;
  }


  /**
   * Sets the value of the 'clientProductId' field.
   * @param value the value to set.
   */
  public void setClientProductId(long value) {
    this.clientProductId = value;
  }

  /**
   * Gets the value of the 'initialBalance' field.
   * @return The value of the 'initialBalance' field.
   */
  public java.math.BigDecimal getInitialBalance() {
    return initialBalance;
  }


  /**
   * Sets the value of the 'initialBalance' field.
   * @param value the value to set.
   */
  public void setInitialBalance(java.math.BigDecimal value) {
    this.initialBalance = value;
  }

  /**
   * Creates a new ClientProductCreatedEvent RecordBuilder.
   * @return A new ClientProductCreatedEvent RecordBuilder
   */
  public static dev.mochahaulier.clientproductservice.event.ClientProductCreatedEvent.Builder newBuilder() {
    return new dev.mochahaulier.clientproductservice.event.ClientProductCreatedEvent.Builder();
  }

  /**
   * Creates a new ClientProductCreatedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ClientProductCreatedEvent RecordBuilder
   */
  public static dev.mochahaulier.clientproductservice.event.ClientProductCreatedEvent.Builder newBuilder(dev.mochahaulier.clientproductservice.event.ClientProductCreatedEvent.Builder other) {
    if (other == null) {
      return new dev.mochahaulier.clientproductservice.event.ClientProductCreatedEvent.Builder();
    } else {
      return new dev.mochahaulier.clientproductservice.event.ClientProductCreatedEvent.Builder(other);
    }
  }

  /**
   * Creates a new ClientProductCreatedEvent RecordBuilder by copying an existing ClientProductCreatedEvent instance.
   * @param other The existing instance to copy.
   * @return A new ClientProductCreatedEvent RecordBuilder
   */
  public static dev.mochahaulier.clientproductservice.event.ClientProductCreatedEvent.Builder newBuilder(dev.mochahaulier.clientproductservice.event.ClientProductCreatedEvent other) {
    if (other == null) {
      return new dev.mochahaulier.clientproductservice.event.ClientProductCreatedEvent.Builder();
    } else {
      return new dev.mochahaulier.clientproductservice.event.ClientProductCreatedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for ClientProductCreatedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ClientProductCreatedEvent>
    implements org.apache.avro.data.RecordBuilder<ClientProductCreatedEvent> {

    private long clientProductId;
    private java.math.BigDecimal initialBalance;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(dev.mochahaulier.clientproductservice.event.ClientProductCreatedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.clientProductId)) {
        this.clientProductId = data().deepCopy(fields()[0].schema(), other.clientProductId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.initialBalance)) {
        this.initialBalance = data().deepCopy(fields()[1].schema(), other.initialBalance);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing ClientProductCreatedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(dev.mochahaulier.clientproductservice.event.ClientProductCreatedEvent other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.clientProductId)) {
        this.clientProductId = data().deepCopy(fields()[0].schema(), other.clientProductId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.initialBalance)) {
        this.initialBalance = data().deepCopy(fields()[1].schema(), other.initialBalance);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'clientProductId' field.
      * @return The value.
      */
    public long getClientProductId() {
      return clientProductId;
    }


    /**
      * Sets the value of the 'clientProductId' field.
      * @param value The value of 'clientProductId'.
      * @return This builder.
      */
    public dev.mochahaulier.clientproductservice.event.ClientProductCreatedEvent.Builder setClientProductId(long value) {
      validate(fields()[0], value);
      this.clientProductId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'clientProductId' field has been set.
      * @return True if the 'clientProductId' field has been set, false otherwise.
      */
    public boolean hasClientProductId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'clientProductId' field.
      * @return This builder.
      */
    public dev.mochahaulier.clientproductservice.event.ClientProductCreatedEvent.Builder clearClientProductId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'initialBalance' field.
      * @return The value.
      */
    public java.math.BigDecimal getInitialBalance() {
      return initialBalance;
    }


    /**
      * Sets the value of the 'initialBalance' field.
      * @param value The value of 'initialBalance'.
      * @return This builder.
      */
    public dev.mochahaulier.clientproductservice.event.ClientProductCreatedEvent.Builder setInitialBalance(java.math.BigDecimal value) {
      validate(fields()[1], value);
      this.initialBalance = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'initialBalance' field has been set.
      * @return True if the 'initialBalance' field has been set, false otherwise.
      */
    public boolean hasInitialBalance() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'initialBalance' field.
      * @return This builder.
      */
    public dev.mochahaulier.clientproductservice.event.ClientProductCreatedEvent.Builder clearInitialBalance() {
      initialBalance = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ClientProductCreatedEvent build() {
      try {
        ClientProductCreatedEvent record = new ClientProductCreatedEvent();
        record.clientProductId = fieldSetFlags()[0] ? this.clientProductId : (java.lang.Long) defaultValue(fields()[0]);
        record.initialBalance = fieldSetFlags()[1] ? this.initialBalance : (java.math.BigDecimal) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ClientProductCreatedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<ClientProductCreatedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ClientProductCreatedEvent>
    READER$ = (org.apache.avro.io.DatumReader<ClientProductCreatedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










