global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['prometheus:9090']
        labels:
          application: 'Prometheus'
  - job_name: 'client-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['client-service:8080']
        labels:
          application: 'Client Service Application'
  - job_name: 'product-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['product-service:8080']
        labels:
          application: 'Product Service Application'
  - job_name: 'clientproduct-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['clientproduct-service:8080']
        labels:
          application: 'Clientproduct Service Application'
  - job_name: 'transaction-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['transaction-service:8080']
        labels:
          application: 'Transaction Service Application'
